spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer


  mail:
    host: smtp.gmail.com
    port: 587
    username: tandemUniversity@gmail.com
    password: tandemUniversity
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  datasource:
    url: jdbc:postgresql://postgres-notification:5432/notificationDB
    username: postgresnotification
    password: postgresnotification
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true




server:
  port: 10002


management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, loggers, metrics, prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      access: read_only
  otlp:
    tracing:
      endpoint: "http://alloy:4318/v1/traces"
      protocol: "http/protobuf"
  tracing:
    sampling:
      probability: 1.0
    export:
      enabled: true


info:
  description: "Микросервис уведомалений"


logging:
  level:
    root: INFO
    org.springframework: debug
    kafka: debug
    org.hibernate: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security: DEBUG
    org.keycloak: DEBUG

