services:

  postgres-headteacher:
    image: postgres:alpine
    container_name: postgres-headteacher
    environment:
      POSTGRES_USER: postgresheadteacher
      POSTGRES_PASSWORD: postgresheadteacher
      POSTGRES_DB: headteacherDB
    ports:
      - "5461:5432"
    volumes:
      - postgres-headteacher_pg_data:/var/lib/postgresql/data


  headteacher-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: headteacher-service
    ports:
      - "11000:10000"
    depends_on:
      - postgres-headteacher
    environment:
      SERVER_PORT: 10000
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-headteacher:5432/headteacherDB
      SPRING_DATASOURCE_USERNAME: postgresheadteacher
      SPRING_DATASOURCE_PASSWORD: postgresheadteacher
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_LIQUIBASE_ENABLED: true



  postgres-keycloak:
    image: postgres:alpine
    container_name: postgres-keycloak
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - "5460:5432"
    volumes:
      - postgres-keycloak_pg_data:/var/lib/postgresql/data



  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-keycloak:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - postgres-keycloak



  postgres-teacher:
    image: postgres:alpine
    container_name: postgres-teacher
    environment:
      POSTGRES_USER: postgresteacher
      POSTGRES_PASSWORD: postgresteacher
      POSTGRES_DB: teacherDB
    ports:
      - "5462:5432"
    volumes:
      - postgres-teacher_pg_data:/var/lib/postgresql/data



  teacher-service:
    build:
      context: ./teacher-service
      dockerfile: Dockerfile
    container_name: teacher-service
    ports:
      - "10001:10001"
    depends_on:
      - postgres-teacher
      - kafka
    environment:
      SERVER_PORT: 10001
      SPRING_DATASOURCE_URL: jdbc:postgresql://teacher-service:5432/teacherDB
      SPRING_DATASOURCE_USERNAME: postgresteacher
      SPRING_DATASOURCE_PASSWORD: postgresteacher
      SPRING_JPA_HIBERNATE_DDL_AUTO: update



  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: unless-stopped


  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8081:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      DYNAMIC_CONFIG_ENABLED: true




  postgres-notification:
    image: postgres:alpine
    container_name: postgres-notification
    environment:
      POSTGRES_USER: postgresnotification
      POSTGRES_PASSWORD: postgresnotification
      POSTGRES_DB: notificationDB
    ports:
      - "5463:5432"
    volumes:
      - postgres-notification_pg_data:/var/lib/postgresql/data




  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    container_name: notification-service
    ports:
      - "10002:10002"
    depends_on:
      - postgres-notification
      - kafka
    environment:
      SERVER_PORT: 10002
      SPRING_DATASOURCE_URL: jdbc:postgresql://notification-service:5432/notificationDB
      SPRING_DATASOURCE_USERNAME: postgresnotification
      SPRING_DATASOURCE_PASSWORD: postgresnotification
      SPRING_JPA_HIBERNATE_DDL_AUTO: update



  postgres-scholarship:
    image: postgres:alpine
    container_name: postgres-scholarship
    environment:
      POSTGRES_USER: postgresscholarship
      POSTGRES_PASSWORD: postgresscholarship
      POSTGRES_DB: scholarshipDB
    ports:
      - "5465:5432"
    volumes:
      - postgres-scholarship_pg_data:/var/lib/postgresql/data


  scholarship-service:
    build:
      context: ./scholarship-service
      dockerfile: Dockerfile
    container_name: scholarship-service
    ports:
      - "10004:10004"
    depends_on:
      - postgres-scholarship
    environment:
      SERVER_PORT: 10004
      SPRING_DATASOURCE_URL: jdbc:postgresql://scholarshop-service:5432/scholarshipDB
      SPRING_DATASOURCE_USERNAME: postgresscholarship
      SPRING_DATASOURCE_PASSWORD: postgresscholarship
      SPRING_JPA_HIBERNATE_DDL_AUTO: update





  student-service:
    build:
      context: ./student-service
      dockerfile: Dockerfile
    container_name: student-service
    ports:
      - "10003:10003"



  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./metrics/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./metrics/prometheus/alert-rules.yml/:/etc/prometheus/alert-rules.yml
      - prometheus_data:/prometheus

    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    depends_on:
      - postgres-keycloak-exporter
      - kafka-exporter
      - postgres-headteacher-exporter
      - postgres-teacher-exporter
      - postgres-notification-exporter




  loki:
    image: grafana/loki:2.9.2
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./metrics/loki/loki-config.yml:/etc/loki/loki-config.yml:ro
      - loki_data:/loki


  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./metrics/alerts/alertmanager.yml:/etc/alertmanager/alertmanager.yml






  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    user: root
    ports:
      - "9080:9080"
      - "4317:4317"
      - "4318:4318"
    volumes:
      - ./metrics/alloy/config.alloy:/etc/alloy/config.alloy:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock



  kafka-exporter:
    image: danielqsj/kafka-exporter
    container_name: kafka-exporter
    command:
      - "--kafka.server=kafka:9092"
    ports:
      - "9308:9308"
    depends_on:
      - kafka


  postgres-headteacher-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: postgres-headteacher-exporter
    depends_on:
      - postgres-headteacher
    environment:
      DATA_SOURCE_NAME: postgresql://postgresheadteacher:postgresteacher@postgres-headteacher:5432/headteacherDB?sslmode=disable
    ports:
      - "9188:9187"




  postgres-teacher-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: postgres-teacher-exporter
    depends_on:
      - postgres-teacher
    environment:
      DATA_SOURCE_NAME: postgresql://postgresteacher:postgresteacher@postgres-teacher:5432/teacherDB?sslmode=disable
    ports:
      - "9189:9187"



  postgres-notification-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: postgres-notification-exporter
    depends_on:
      - postgres-notification
    environment:
      DATA_SOURCE_NAME: postgresql://postgresnotification:postgresnotification@postgres-notification:5432/notificationB?sslmode=disable
    ports:
      - "9190:9187"


  postgres-keycloak-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: postgres-keycloak-exporter
    depends_on:
      - postgres-keycloak
    environment:
      DATA_SOURCE_NAME: postgresql://keycloak:keyclaok@postgres-keycloak:5432/keycloak?sslmode=disable
    ports:
      - "9191:9187"





  grafana:
    image: grafana/grafana:10.4.2
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./metrics/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
      - loki
      - tempo
      - alloy






volumes:
  postgres-keycloak_pg_data:
  postgres-headteacher_pg_data:
  postgres-teacher_pg_data:
  postgres-notification_pg_data:
  postgres-scholarship_pg_data:
  loki_data:
  prometheus_data:
  tempo_data:
  grafana_data:
