spring:
  application:
    name: student-service

  security:
    oauth2:
      client:
        registration:
          student-service:
            client-id: teacher
            client-secret: SSgIengwoieasfn234gje
            authorization-grant-type: client-credentials
            provider: keycloak
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/tandem
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/tandem


server:
  port: 10003

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    enable:
      all: true

  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://alloy:4318/v1/traces

logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
    org.hibernate: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security: DEBUG
    org.keycloak: DEBUG


