spring:
  application:
    name: student-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://kafka:8080/realms/tandem


server:
  port: 10003

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    enable:
      all: true

  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://alloy:4318/v1/traces


