spring:
  application:
    name: headteacher-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/tandem


  springdoc:
    swagger-ui:
      oauth:
        client-id: headteacher
        client-secret: Ie7JLRosPM5ALvHBR50ITr3p3336Ocy9
        scopes: openid,profile,email




  datasource:
    url: jdbc:postgresql://postgres-headteacher:5432/headteacherDB
    username: postgresheadteacher
    password: postgresheadteacher
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true

server:
  port: 10000



management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    enable:
      all: true

  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://alloy:4318/v1/traces
