apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.secret.name}}
stringData:
  SPRING_DATASOURCE_USERNAME: {{ .Values.secret.DB_USER | quote }}
  SPRING_DATASOURCE_PASSWORD: {{.Values.secret.DB_PASSWORD | quote}}
