apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  KEYCLOAK_ADMIN: {{ .Values.keycloak.adminUser | quote }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.keycloak.adminPassword | quote }}