global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'UniversityTandem@gmail.com'
  smtp_auth_username: 'UniversityTandem@gmail.com'
  smtp_auth_password: 'APP_PASSWORD'
  smtp_require_tls: true

route:
  receiver: 'developers'
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 15m

receivers:
  - name: 'developers'
    email_configs:
      - to: 'UniversityTandemHelp@gmail.com'
        send_resolved: true