spring:
  application:
    name: scholarship-service

info:
  description: "Микросервис стипендий"

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, loggers, metrics, prometheus
  endpoint:
    probes:
      enabled: true
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
    export:
      enabled: true