spring:
  application:
    name: scholarship-service

  datasource:
    url: jdbc:postgresql://scholarship-teacher:5432/scholarshipDB
    username: scholarshipteacher
    password: scholarshipteacher
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, loggers, metrics, prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      access: read_only
  otlp:
    tracing:
      endpoint: "http://alloy:4318/v1/traces"
      protocol: "http/protobuf"
  tracing:
    sampling:
      probability: 1.0
    export:
      enabled: true


info:
  description: "Микросервис стипендий"


logging:
  level:
    root: debug
    org.springframework: debug
    org.hibernate: debug
    org.hibernate.SQL: DEBUG


